# Generated by Django 3.0.4 on 2020-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.CharField(default='0', max_length=20, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_num',
            field=models.CharField(default='0', max_length=20, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titleimg',
            field=models.ImageField(blank=True, null=True, upload_to='articleimg', verbose_name='标题图'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authorimg', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Against',
            field=models.CharField(default='0', max_length=20, verbose_name='反对数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='agree',
            field=models.CharField(default='0', max_length=20, verbose_name='赞同数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
