# Generated by Django 3.0.4 on 2020-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneerapp', '0003_auto_20200309_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='type_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='文章类别'),
        ),
        migrations.AlterField(
            model_name='authortype',
            name='type_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='作者类别'),
        ),
        migrations.AlterField(
            model_name='thematictype',
            name='type_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='专题类别'),
        ),
    ]
