# Generated by Django 3.0.3 on 2020-03-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='部门名')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='员工名')),
                ('gender', models.CharField(blank=True, max_length=5, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=5, null=True, verbose_name='年龄')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('salary', models.IntegerField(max_length=20, verbose_name='工资')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depars', to='manageapp.Department', verbose_name='部门')),
            ],
        ),
    ]
