# Generated by Django 3.0.3 on 2020-03-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(verbose_name='工资'),
        ),
    ]
