# Generated by Django 3.0.3 on 2020-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200216_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
