# Generated by Django 3.0.3 on 2020-02-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200216_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'verbose_name': '投票表', 'verbose_name_plural': '投票表'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': '选项表', 'verbose_name_plural': '选项表'},
        ),
    ]
