# Generated by Django 3.0.3 on 2020-02-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('regist_date', models.DateField(auto_now_add=True, verbose_name='注册日期')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('sumary', models.TextField(verbose_name='正文')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '用户模型类a',
                'verbose_name_plural': '用户模型类s',
                'db_table': '用户类',
                'ordering': ['-telephone'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='wjw', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(blank=True, db_column='description', help_text='请输入书籍备注嘻嘻', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='booktest.Book'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名')),
                ('article', models.ManyToManyField(to='booktest.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Concact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(default='1815095781@qq.com', max_length=254)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='con', to='booktest.Account')),
            ],
        ),
    ]
