# Generated by Django 3.0.3 on 2020-03-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=20, verbose_name='书籍名字'),
        ),
        migrations.AlterField(
            model_name='goodimgs',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='shop.Good', verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='goodimgs',
            name='img',
            field=models.ImageField(upload_to='goodimg', verbose_name='书籍展示图'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ManyToManyField(to='shop.Good', verbose_name='订阅书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
