# Generated by Django 3.0.3 on 2020-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('max_temperature', models.CharField(max_length=10, verbose_name='最高温度')),
                ('min_temperature', models.CharField(max_length=10, verbose_name='最低温度')),
                ('condition', models.CharField(max_length=10, verbose_name='天气')),
                ('wind', models.CharField(max_length=20, verbose_name='风力')),
                ('uv', models.CharField(max_length=20, verbose_name='紫外线强度')),
                ('air', models.CharField(max_length=20, verbose_name='空气质量')),
            ],
        ),
    ]
